from django.urls import path

from password_manager_admin import views

urlpatterns = [
    path("register", views.RegisterAdminUser.as_view(), name='register'),
    path("login", views.LoginAdminUser.as_view(), name='login'),
    path("refresh_token", views.RefreshToken.as_view(), name='refresh_token'),
    path("admin_dashboard", views.Dashboard.as_view(), name='admin_dashboard'),
    path("users", views.ManageUsers.as_view(), name='users'),
    path("manage_users", views.UsersDashboard.as_view(), name='manage_users'),
    path("policies", views.PasswordPolicies.as_view(), name='policies'),
    path("policy-details", views.PasswordPolicyDetails.as_view(), name='policy-details'),
    path("manage_policies", views.ManagePasswordPolicies.as_view(), name='manage_policies'),
    path("violations", views.PolicyViolations.as_view(), name='violations'),
    path("violation-details", views.PolicyViolationDetails.as_view(), name='violation-details'),
    path("assignments", views.PolicyAssignments.as_view(), name='assignments'),
    path("assignment-details", views.PolicyAssignmentDetails.as_view(), name='assignment-details'),
    path("manage_assignments", views.ManageAssignment.as_view(), name='assignment-details'),
    path("breach-databases", views.BreachDatabases.as_view(), name='breach-databases'),
    path("breach-database-details", views.BreachDatabaseDetails.as_view(), name='breach-database-details'),
    path("get_breaches", views.HIBPBreaches.as_view(), name='get_breached'),
    path("get_breach_details", views.HIBPBreachDetails.as_view(), name='get_breach_details'),
    path("breached-hashes", views.BreachedPasswordHashes.as_view(), name='breached-hashes'),
    path("breached-hash-details", views.BreachedPasswordHashDetails.as_view(), name='breached-hashes-details'),
    path("manage_breaches", views.ManageBreaches.as_view(), name='manage_breaches'),
    path("audit-logs", views.SecurityAuditLogs.as_view(), name='audit-logs'),
    path("audit-log-details", views.SecurityAuditLogDetails.as_view(), name='audit-log-details'),
    path("anomaly-alerts", views.AnomalyAlerts.as_view(), name='anomaly-alerts'),
    path("anomaly-alert-details", views.AnomalyAlertDetails.as_view(), name='anomaly-alert-details'),
    path("configurations", views.AnalyzerConfigurations.as_view(), name='configurations'),
    path("configurations-details", views.AnalyzerConfigurationDetails.as_view(), name='configurations-details'),
    path("wordlists", views.DictionaryWordlists.as_view(), name='wordlists'),
    path("wordlists-details", views.DictionaryWordlistDetails.as_view(), name='wordlists-details'),
    path("patterns", views.KeyboardPatterns.as_view(), name='patterns'),
    path("pattern-details", views.KeyboardPatternDetails.as_view(), name='pattern-details'),
]